### ISSUE TITLE
Create a PyPI package

### ISSUE THREAD

**Issue by ArneBachmannDLR** [tmkontra/compatlib#2]
... to allow installation via pip.

**Comment by ttymck** [comment]
Hi @ArneBachmannDLR, thanks for your interest. Unfortunately, this is more of an experimental project, and I would prefer users have to go through the extra steps if they want to integrate this into their codebase -- this isn't something I'd like to officially support or endorse for "production use" :smile:

You are of course welcome to package this as you'd like: as freely permitted by the MIT License.
